### ISSUE TITLE
Action Required - Your team contact from Project Registry has undeliverable email

### ISSUE THREAD

**Issue by ShellyXueHan** [bcgov/sbc-maximus-services#12]
Hello team,
 
We noticed that Jam Hamidi is listed as both Product Owner and Technical Lead for your Openshift project set SBC Maximus Services `3a0694-*`. For lack of a better way to reach out to you, we are creating a GitHub issue hoping to get your attention. While Jam is not working on this project anymore, we ask you to update the contact info with us at PlatformServicesTeam@gov.bc.ca ASAP to ensure you get notified properly with platform related news!
 
 
Regards,

Platform Services Team
OCIO Digital Office
Ministry of Citizens’ Services

**Comment by bryce-mcmath** [comment]
@ShellyXueHan I am no longer on the team that maintains this repo (haven't been for a year and a half) but I believe Cyril Bravo still is. Samuel Amos and Harry Maynard both moved on from this team as well

**Comment by skylermcnamee-hibc** [comment]
We've reached out at the email address provided to continue this conversation, so I'll close this issue.
